name: Web Vulnerability Scan
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OWASP ZAP CLI
        run: |
          wget https://github.com/Grunny/ZAP-CLI/releases/download/2.9.0/zap-cli-linux -O zap-cli
          chmod +x zap-cli
          sudo mv zap-cli /usr/local/bin/zap-cli

      - name: Start ZAP
        run: |
          # Start ZAP in daemon mode
          zap.sh -daemon -config api.disablekey=true
          sleep 15  # Give ZAP some time to start

      - name: Run ZAP Scan
        run: |
          # Replace 'https://www.reddit.com/' with your target URL
          zap-cli quick-scan --self-contained https://www.reddit.com/

      - name: Shutdown ZAP
        run: |
          zap-cli shutdown
