name: Security Scan
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4     # Must complete before next run
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@main
        with:
          target: https://redit.com
          exit-code: '0'    # Continue even if vulnerabilities found

      - name: Save Report
        run: |
          trivy --format table https://reddit.com > report.txt
          date >> report.txt  # Append timestamp

      - uses: EndBug/add-and-commit@v9
        with:
          add: report.txt
          message: "Auto Security Report - $(date +'%Y-%m-%d %H:%M')"
