name: Security Scan
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4     # Must complete before next run
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: "nginx:latest"  # Example: Replace with an actual container image
          exit-code: '0'    

      - name: Save Report
        run: |
          trivy fs . > report.txt
          date >> report.txt  # Append timestamp

      - uses: EndBug/add-and-commit@v9
        with:
          add: report.txt
          message: "Auto Security Report - $(date +'%Y-%m-%d %H:%M')"
