name: Web Vulnerability Scan
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install "zapcli" "requests==2.20.1" "urllib3<1.25"
          zap-cli -h  # Show help since --version doesn't exist

      - name: Start OWASP ZAP (Docker)
        run: |
          docker run -d --name zap -p 8080:8080 owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
          sleep 15  # Wait for ZAP to start

      - name: Run ZAP Quick Scan
        run: |
          zap-cli -p 8080 quick-scan --self-contained https://www.reddit.com

      - name: Shutdown OWASP ZAP
        run: |
          docker stop zap
          docker rm zap
